version: '3.8'
services:
  calculatorapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"      # Mapeia a porta 80 do contêiner para a porta 80 do host
      - "443:443"    # Mapeia a porta 443 do contêiner para a porta 443 do host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
